//form Project Euler problem 2
//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
//Ans 4613732
#include <iostream>
using namespace std;
int main()
{
    int series[10000],i,j,k=2,sum=0;
    series[1]=1;
    series[2]=1;
    for(i=3;i<1000000;i++)
    {
        series[i] = series[i-1] + series[i-2];
        j = series[i];
        if(j%2==0) sum += j;
        if(j>4000000) break;
    }
    printf("%d",sum); 
}


